# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170427_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
