# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170427_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discretionary_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group_person_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='miles_willing_to_travel',
            field=models.IntegerField(default=2),
        ),
    ]
