# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170427_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group_person_count',
        ),
    ]
